name: empirical
channels:
  - defaults
  - conda-forge
dependencies:
  - pip:
    - hiplot==0.1.23
    - pandas-profiling==2.10.1
    - phik==0.11.0
    - plotly==4.14.3
    - matplotlib==3.3.4
    - seaborn==0.11.1    
